forge "https://forgeapi.puppetlabs.com"
mod 'puppetlabs/apache'
# puppetlabs-postgresql needs to add support for fedora 23 :)
# mod 'puppetlabs/postgresql'
#
mod 'puppetlabs/postgresql',
  :git => 'git://github.com/ajmaidak/puppetlabs-postgresql.git',
  :ref => 'fedora23'
mod 'puppetlabs/git'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/firewall'
mod 'jfryman/selinux'
mod 'camptocamp/systemd'
mod 'puppet-ttrss',
  :git => 'git://github.com/ajmaidak/puppet-ttrss.git'
