fixtures:
  repositories:
    stdlib: "http://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo: "http://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    git: "http://github.com/puppetlabs/puppetlabs-git.git"
  symlinks:
    "ttrss": "#{source_dir}"
